// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'bitcoin.dart';
import 'bolt11.dart';
import 'error.dart';
import 'mint.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'payment_request.dart';
import 'token.dart';
part 'wallet.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `mint_url`, `unit`, `update_balance_streams`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `into`, `partial_cmp`, `try_into`, `try_into`, `try_into`

ParseInputResult parseInput({required String input}) =>
    RustLib.instance.api.crateApiWalletParseInput(input: input);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MultiMintWallet>>
abstract class MultiMintWallet implements RustOpaqueInterface {
  Future<void> addMint({required String mintUrl});

  Future<void> addWallet({required Wallet wallet});

  String get unit;

  set unit(String unit);

  Future<List<Mint>> availableMints({BigInt? amount, List<String>? mintUrls});

  Future<Wallet> createOrGetWallet({required String mintUrl});

  Future<List<MintQuote>> getActiveMintQuotes({String? mintUrl});

  /// Get unspent authentication proofs for a specific mint
  Future<List<AuthProof>> getUnspentAuthProofs({required String mintUrl});

  Future<Wallet?> getWallet({required String mintUrl});

  Future<List<Mint>> listMints();

  Future<List<Transaction>> listTransactions(
      {TransactionDirection? direction, String? mintUrl});

  Future<List<Wallet>> listWallets();

  /// Mint blind auth tokens for a specific mint
  ///
  /// Blind auth tokens are required for protected mint operations.
  /// A Clear Auth Token (CAT) must be set before calling this method.
  ///
  /// # Arguments
  /// * `mint_url` - The mint URL to mint blind auth tokens from
  /// * `amount` - The number of blind auth tokens to mint
  ///
  /// # Returns
  /// A vector of AuthProof that can be used for authenticated operations
  Future<List<AuthProof>> mintBlindAuth(
      {required String mintUrl, required BigInt amount});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new multi-mint wallet from a BIP39 mnemonic
  static Future<MultiMintWallet> newInstance(
          {required String unit,
          required String mnemonic,
          BigInt? targetProofCount,
          required WalletDatabase db}) =>
      RustLib.instance.api.crateApiWalletMultiMintWalletNew(
          unit: unit,
          mnemonic: mnemonic,
          targetProofCount: targetProofCount,
          db: db);

  Future<void> reclaimReserved();

  /// Refresh the access token using the stored refresh token
  Future<void> refreshAccessToken({required String mintUrl});

  Future<void> removeMint({required String mintUrl});

  Future<Wallet?> selectWallet({BigInt? amount, List<String>? mintUrls});

  /// Set the Clear Auth Token (CAT) for a specific mint
  ///
  /// The CAT is an OIDC/JWT token from the authentication provider (e.g., Keycloak)
  /// that is required for minting blind auth tokens.
  Future<void> setCat({required String mintUrl, required String cat});

  /// Set the refresh token for a specific mint
  ///
  /// The refresh token is used to obtain new CATs when they expire.
  Future<void> setRefreshToken(
      {required String mintUrl, required String refreshToken});

  Stream<BigInt> streamBalance();

  Future<BigInt> totalBalance();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PreparedSend>>
abstract class PreparedSend implements RustOpaqueInterface {
  BigInt get amount;

  BigInt get fee;

  BigInt get sendFee;

  BigInt get swapFee;

  set amount(BigInt amount);

  set fee(BigInt fee);

  set sendFee(BigInt sendFee);

  set swapFee(BigInt swapFee);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>
abstract class Wallet implements RustOpaqueInterface {
  String get mintUrl;

  String get unit;

  set mintUrl(String mintUrl);

  set unit(String unit);

  Future<BigInt> balance();

  Future<void> cancelSend({required PreparedSend send});

  Future<void> checkAllMintQuotes();

  Future<void> checkPendingMeltQuotes();

  Future<void> checkPendingTransactions();

  /// Fetch mint info from the mint server
  ///
  /// This always makes a network call to fetch fresh mint info.
  Future<Mint?> fetchMintInfo();

  Future<List<MintQuote>> getActiveMintQuotes();

  Future<Mint> getMint();

  /// Get unspent authentication proofs for protected mint endpoints
  Future<List<AuthProof>> getUnspentAuthProofs();

  Future<bool> isTokenSpent({required Token token});

  Future<List<Transaction>> listTransactions({TransactionDirection? direction});

  Future<BigInt> melt({required MeltQuote quote});

  Future<MeltQuote> meltBolt12Quote(
      {required String request, MeltOptions? opts});

  Future<MeltQuote> meltQuote({required String request, MeltOptions? opts});

  Stream<MintQuote> mint({required BigInt amount, String? description});

  /// Create a new wallet from a BIP39 mnemonic
  factory Wallet(
          {required String mintUrl,
          required String unit,
          required String mnemonic,
          BigInt? targetProofCount,
          required WalletDatabase db}) =>
      RustLib.instance.api.crateApiWalletWalletNew(
          mintUrl: mintUrl,
          unit: unit,
          mnemonic: mnemonic,
          targetProofCount: targetProofCount,
          db: db);

  Future<void> payRequest(
      {required PreparedSend send, String? memo, bool? includeMemo});

  Future<PreparedSend> preparePayRequest({required PaymentRequest request});

  Future<PreparedSend> prepareSend({required BigInt amount, SendOptions? opts});

  Future<BigInt> receive({required Token token, ReceiveOptions? opts});

  Future<void> reclaimReserved();

  Future<void> reclaimSend({required Token token});

  Future<void> restore();

  Future<void> revertTransaction({required String transactionId});

  Future<Token> send(
      {required PreparedSend send, String? memo, bool? includeMemo});

  Stream<BigInt> streamBalance();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletDatabase>>
abstract class WalletDatabase implements RustOpaqueInterface {
  DatabaseType get backendType;

  String? get path;

  String? get url;

  set backendType(DatabaseType backendType);

  set path(String? path);

  set url(String? url);

  /// Check if this is a SQLite database
  bool isSqlite();

  /// Check if this is a Supabase database
  bool isSupabase();

  Future<List<Mint>> listMints({String? unit, String? mnemonic});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new SQLite database (backwards compatible)
  static Future<WalletDatabase> newInstance({required String path}) =>
      RustLib.instance.api.crateApiWalletWalletDatabaseNew(path: path);

  /// Create a new Supabase database
  static Future<WalletDatabase> newSupabase(
          {required String url, required String apiKey}) =>
      RustLib.instance.api
          .crateApiWalletWalletDatabaseNewSupabase(url: url, apiKey: apiKey);

  /// Create a new Supabase database with separate API key and JWT token
  ///
  /// - `api_key`: The Supabase project API key (used in `apikey` header)
  /// - `jwt_token`: Optional JWT token for user authentication (used in `Authorization: Bearer` header)
  ///
  /// Use this method when you need to authenticate with Keycloak or another OIDC provider
  /// while still using Supabase for data storage.
  static Future<WalletDatabase> newSupabaseWithJwt(
          {required String url, required String apiKey, String? jwtToken}) =>
      RustLib.instance.api.crateApiWalletWalletDatabaseNewSupabaseWithJwt(
          url: url, apiKey: apiKey, jwtToken: jwtToken);

  Future<void> removeMint({required String mintUrl});
}

/// Authentication proof for protected mint endpoints
class AuthProof {
  /// Keyset ID
  final String keysetId;

  /// Secret message
  final String secret;

  /// Unblinded signature (C)
  final String c;

  /// Y value (hash_to_curve of secret)
  final String y;

  const AuthProof({
    required this.keysetId,
    required this.secret,
    required this.c,
    required this.y,
  });

  @override
  int get hashCode =>
      keysetId.hashCode ^ secret.hashCode ^ c.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthProof &&
          runtimeType == other.runtimeType &&
          keysetId == other.keysetId &&
          secret == other.secret &&
          c == other.c &&
          y == other.y;
}

/// Database backend type - exposed to Dart for runtime type checking
enum DatabaseType {
  /// Local SQLite database
  sqlite,

  /// Remote Supabase database
  supabase,
  ;
}

class MeltOptions {
  final BigInt? mpp;
  final BigInt? amountlessMsat;

  const MeltOptions({
    this.mpp,
    this.amountlessMsat,
  });

  @override
  int get hashCode => mpp.hashCode ^ amountlessMsat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeltOptions &&
          runtimeType == other.runtimeType &&
          mpp == other.mpp &&
          amountlessMsat == other.amountlessMsat;
}

class MeltQuote {
  final String id;
  final String request;
  final BigInt amount;
  final BigInt feeReserve;
  final BigInt expiry;

  const MeltQuote({
    required this.id,
    required this.request,
    required this.amount,
    required this.feeReserve,
    required this.expiry,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      request.hashCode ^
      amount.hashCode ^
      feeReserve.hashCode ^
      expiry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeltQuote &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          request == other.request &&
          amount == other.amount &&
          feeReserve == other.feeReserve &&
          expiry == other.expiry;
}

class MintQuote {
  final String id;
  final String request;
  final BigInt? amount;
  final BigInt? expiry;
  final MintQuoteState state;
  final Token? token;
  final String? error;

  const MintQuote({
    required this.id,
    required this.request,
    this.amount,
    this.expiry,
    required this.state,
    this.token,
    this.error,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      request.hashCode ^
      amount.hashCode ^
      expiry.hashCode ^
      state.hashCode ^
      token.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintQuote &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          request == other.request &&
          amount == other.amount &&
          expiry == other.expiry &&
          state == other.state &&
          token == other.token &&
          error == other.error;
}

enum MintQuoteState {
  unpaid,
  paid,
  issued,
  error,
  ;
}

@freezed
sealed class ParseInputResult with _$ParseInputResult {
  const ParseInputResult._();

  const factory ParseInputResult.bitcoinAddress(
    BitcoinAddress field0,
  ) = ParseInputResult_BitcoinAddress;
  const factory ParseInputResult.bolt11Invoice(
    Bolt11Invoice field0,
  ) = ParseInputResult_Bolt11Invoice;
  const factory ParseInputResult.paymentRequest(
    PaymentRequest field0,
  ) = ParseInputResult_PaymentRequest;
  const factory ParseInputResult.token(
    Token field0,
  ) = ParseInputResult_Token;
}

class ReceiveOptions {
  final List<String>? signingKeys;
  final List<String>? preimages;
  final Map<String, String>? metdata;

  const ReceiveOptions({
    this.signingKeys,
    this.preimages,
    this.metdata,
  });

  static Future<ReceiveOptions> default_() =>
      RustLib.instance.api.crateApiWalletReceiveOptionsDefault();

  @override
  int get hashCode =>
      signingKeys.hashCode ^ preimages.hashCode ^ metdata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiveOptions &&
          runtimeType == other.runtimeType &&
          signingKeys == other.signingKeys &&
          preimages == other.preimages &&
          metdata == other.metdata;
}

class SendOptions {
  final String? memo;
  final bool? includeMemo;
  final String? pubkey;
  final Map<String, String>? metadata;

  const SendOptions({
    this.memo,
    this.includeMemo,
    this.pubkey,
    this.metadata,
  });

  static Future<SendOptions> default_() =>
      RustLib.instance.api.crateApiWalletSendOptionsDefault();

  @override
  int get hashCode =>
      memo.hashCode ^
      includeMemo.hashCode ^
      pubkey.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendOptions &&
          runtimeType == other.runtimeType &&
          memo == other.memo &&
          includeMemo == other.includeMemo &&
          pubkey == other.pubkey &&
          metadata == other.metadata;
}

class Transaction {
  final String id;
  final String mintUrl;
  final TransactionDirection direction;
  final BigInt amount;
  final BigInt fee;
  final String unit;
  final List<String> ys;
  final BigInt timestamp;
  final String? memo;
  final Map<String, String> metadata;
  final TransactionStatus status;

  const Transaction({
    required this.id,
    required this.mintUrl,
    required this.direction,
    required this.amount,
    required this.fee,
    required this.unit,
    required this.ys,
    required this.timestamp,
    this.memo,
    required this.metadata,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mintUrl.hashCode ^
      direction.hashCode ^
      amount.hashCode ^
      fee.hashCode ^
      unit.hashCode ^
      ys.hashCode ^
      timestamp.hashCode ^
      memo.hashCode ^
      metadata.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Transaction &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mintUrl == other.mintUrl &&
          direction == other.direction &&
          amount == other.amount &&
          fee == other.fee &&
          unit == other.unit &&
          ys == other.ys &&
          timestamp == other.timestamp &&
          memo == other.memo &&
          metadata == other.metadata &&
          status == other.status;
}

enum TransactionDirection {
  incoming,
  outgoing,
  ;
}

enum TransactionStatus {
  pending,
  settled,
  ;
}
